version: "2"
plugins:
  fixme:
    enabled: true
  radon:
    enabled: true
  sonar-python:
    enabled: true
    config:
      tests_patterns:
        - uaaextras/tests.py

exclude_patterns:
-  uaaextras/tests.py
